name: cooler-name

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: cooler step-name
        run: echo "Hallo Welt!"
      - name: Ordner erstellen
        run: mkdir ordner
      - name: listen
        run: ls
